# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17eb5788a7e4c3ed4806cab25e32d555f08ac0e26e4ab04d1e3bf3cd92f968c13207a78c7865f02239c5e118f70e98a1823379361b83ad462955e10f7e2648d0

test:
  secret_key_base: 1670973ee3a79a356f4942dd6cf1acc14f367eba5d605cff95c62ce6ad60d84f950b77c759bb44290d3975304b38e29eb7a9d1e916739b16c2d25a718ef48849

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
